name: "Testing github actions"
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        run: echo "Starting the World"
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun --version
      - name: Installing dependencies
        run: bun install
      - name: Building the Project
        run: bun run build
